### ISSUE TITLE
New rule for : Linting Rule for LABELS PARAMETERS in Param Label structure

### ISSUE THREAD

**Issue by gargana** [aws-quickstart/qs-cfn-lint-rules#12]
Having bad indentation can break document generation:

```
    - Label:
        default: Aerospike configuration
      Parameters:
      - NumberOfInstances
      - Tenancy
      - EnableCloudWatch
      - InstanceType
      - EBS
      - NamespaceFile
      - FeatureKeyFile
    - Label:
        default: Linux bastion configuration
        Parameters:
          - BastionAMIOS
          - BastionInstanceType
          - NumBastionHosts
```
